apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
      - name: service1
        image: jcudak/service1:latest
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5001
  selector:
    app: service1
